name: Build and test

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
      - v2.0-devel # TODO: Remove

jobs:
  build-and-test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        compiler:
        - { name: "g++-4.9", cxx: "g++-4.9" }
        - { name: "g++-5", cxx: "g++-5" }
        - { name: "clang-3.9", cxx: "clang++-3.9" }

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
           sudo apt-get update -q
           sudo apt-get install -y libeigen3-dev libopenmpi-dev libboost-all-dev
           sudo apt-get install -y ${{ matrix.compiler.name }}

    - name: Install Doxygen
      if: startsWith(matrix.cxx_compiler.name, 'clang') == true
      run: sudo apt-get install -y doxygen

    - name: Install libcommute
      run: |
           git clone https://github.com/krivenko/libcommute
           mkdir libcommute.build && cd libcommute.build
           cmake ../libcommute                                                 \
              -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/libcommute.ins        \
              -DTESTS=OFF                                                      \
              -DEXAMPLES=OFF
           make install

    - name: Build
      env:
        CXX: ${{ matrix.compiler.cxx }}
      run: |
           mkdir build
           cd build
           cmake -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/installed          \
                 -Dlibcommute_DIR=${GITHUB_WORKSPACE}/libcommute.ins/lib/cmake \
                 -DTesting=ON                                                  \
                 -DProgs=ON                                                    \
                 -Dprogs_list="anderson;hubbard2d" ..
           make VERBOSE=1
           make doc

    - name: Run unit tests
      run: |
           cd build
           CTEST_OUTPUT_ON_FAILURE=1 make test

    - name: Install
      run: |
           cd build
           make install

    - name: Deploy documentation
      if: |
          github.ref == 'refs/heads/master' &&
          startsWith(matrix.cxx_compiler.name, 'clang') == true
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: installed/share/doc/pomerol
